name: Docker Image Build And Push

on:
  workflow_dispatch:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      docker_user:
        required: true
        type: string
      docker_password:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ inputs.docker_user }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
    - name: login docker
      run: echo ${{ inputs.docker_password }} | docker login -u ${{ inputs.docker_user }} --password-stdin
    - name: Push the Docker image
      run: docker push ${{ inputs.docker_user }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
