name: Openwrt Build

on:
  workflow_dispatch:
    # inputs:
    #   check_out:
    #     required: true
    #     type: string
    #   config_http_path:
    #     required: true
    #     type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: apt update and install
      run: sudo apt update && sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget 
    - name: git clone openwrt
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.3
        git status
    - name: openwrt feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: openwrt config
      run: |
        wget https://raw.githubusercontent.com/brightvip/docker-nginx/main/other/configcmcc3000m -O openwrt/.config
        cat openwrt/.config
    - name: openwrt make download
      run: |
        cd openwrt
        make download -j8
    - name: openwrt make
      run: |
        cd openwrt
        make -j8
    - name: Store packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: |
          openwrt/bin/targets/
          
