name: Openwrt Build v23.05.3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: openwrt config
      run: |
        pwd
        ls
        cat other/openwrt/v23.05.3/configcmcc3000m
          
