name: Openwrt Build v23.05.3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: apt update and install
      run: sudo apt update && sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget 
    - name: git clone openwrt
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.3
        git status
    - name: openwrt feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - uses: actions/checkout@v4
    - name: openwrt config
      run: |
        mv  other/openwrt/v23.05.3/configcmcc3000m openwrt/.config
        cat openwrt/.config
    - name: openwrt make download
      run: |
        cd openwrt
        make download -j$(nproc)
    - name: openwrt make
      run: |
        mv  other/openwrt/v23.05.3/999-issue-23621.patch openwrt/feeds/packages/libs/libpfring/patches/999-issue-23621.patch
        cat openwrt/feeds/packages/libs/libpfring/patches/999-issue-23621.patch
        cd openwrt
        make -j$(nproc)
    - name: Store packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: |
          openwrt/bin/targets/
          
