name: Openwrt Build

on:
  workflow_dispatch:
    inputs:
      check_out:
        required: true
        type: string
      config_http_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: apt update and install
      run: sudo apt update && sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget 
    - name: git clone openwrt
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.3
        git status
    - name: openwrt feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: openwrt config
      run: |
        wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/config.buildinfo -O openwrt/.config
        cat openwrt/.config
    # - name: Push the Docker image
    #   run: docker push ${{ inputs.docker_user }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
